name: updatable_ticker_sample
description: "A sample app demonstrating the Flutter Updatable Ticker library."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.19.6 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local dependency to the Ticker library
  ipsum: ^1.0.1
  updatable_ticker:
    path: ../updatable_ticker_library

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
